tap 'git-duet/tap'
tap 'AdoptOpenJDK/openjdk'

cask 'AdoptOpenJDK/openjdk/adoptopenjdk13'
cask 'iterm2'
cask 'textmate'
cask 'shiftit'
cask 'flycut'
cask 'intellij-idea'
cask 'docker'
cask 'google-chrome'
cask 'slack'

brew 'rbenv'
brew 'python'
brew 'node'
brew 'yarn'
brew 'wget'
brew 'watch'
brew 'tree'
brew 'vim'
brew 'jq'
brew 'shellcheck'
brew 'git-duet'
brew 'node'
