#!/bin/bash

SCRIPTS_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )/scripts" && pwd )"

$SCRIPTS_DIRECTORY/homebrew
$SCRIPTS_DIRECTORY/key_repeat_rate
$SCRIPTS_DIRECTORY/bash_it
$SCRIPTS_DIRECTORY/bash_profile
$SCRIPTS_DIRECTORY/git_aliases
$SCRIPTS_DIRECTORY/brew_bundle
$SCRIPTS_DIRECTORY/ruby
$SCRIPTS_DIRECTORY/vim
$SCRIPTS_DIRECTORY/disable_gatekeeper

